# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Requested

on:
  workflow_run:
    workflows: [CI]
    types:
      - requested
  pull_request_target:
    types:
      - labeled

jobs:
  check-pr-labels:
    # Even though job conditionals are difficult to debug, this will reduce the number of unnecessary runs
    if: |
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.event == 'pull_request' &&
       github.event.workflow_run.status == 'completed' && 
       github.event.workflow_run.conclusion == 'action_required') ||
      (github.event_name == 'pull_request_target' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'ci-approved')
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: printenv
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials:
            false
      - name: Check PR Labels (workflow_run)
        id: check-pr-labels-1
        if: |
          github.event_name == 'workflow_run' && 
          github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.status == 'completed' && 
          github.event.workflow_run.conclusion == 'action_required'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          set +e
          gh pr view $PR_NUMBER --json labels -q '.labels[].name' | grep -q 'ci-approved'
          exitcode="$?"
          if [ $exitcode -ne 0 ]; then
            echo "No ci-approved label set on PR #$PR_NUMBER. Will not auto-approve.";
            exit 0;
          else
            echo "Found 'ci-approved' label on PR #$PR_NUMBER. Auto-approving workflow run $RUN_ID.";
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
          echo "RUN_ID=$RUN_ID" >> "$GITHUB_ENV"
      - name: Check PR Labels (pull_request_target)
        id: check-pr-labels-2
        if: |
          github.event_name == 'pull_request_target' &&
          github.event.action == 'labeled' &&
          github.event.label.name == 'ci-approved'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          set +e
          echo "Found 'ci-approved' label on PR #$PR_NUMBER.";
          RUN_ID=$(gh run list -L 1 -c $SHA -s action_required --json databaseId --jq '.[].databaseId')
          if [ -z "$RUN_ID" ]; then
            echo "No workflow run found for SHA $SHA";
            exit 0;
          else
            echo "Auto-approving workflow run $RUN_ID.";
          fi;
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
          echo "RUN_ID=$RUN_ID" >> "$GITHUB_ENV"
      - name: Approve Workflow Run
        if: env.RUN_ID != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          echo "Approving workflow run $RUN_ID for PR $PR_NUMBER";
          gh api --method POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            /repos/$REPOSITORY/actions/runs/$RUN_ID/approve
