name: Release

# Triggered when a draft released is "published" (not a draft anymore)
on:
  release:
    types: [ published ]

jobs:
  docker-app-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore gradle.properties
          env:
            GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
          shell: bash
          run: |
            mkdir -p ~/.gradle/
            echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
            echo "${GRADLE_PROPERTIES}" >> ~/.gradle/gradle.properties
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew clients:publish